version: '2'
services:
    nginx:
        image: nginx
        container_name: nginx-weather
        hostname: nginx-weather
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - weather
    weather:
        build: .
        container_name: weather
        restart: always
        expose:
            - "8000"
